services:
  - type: web
    name: restaurant-chatbot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false 